### ISSUE TITLE
Dyslexia font?

### ISSUE THREAD

**Issue by evesucl** [sharpchi/moodle-local_accessibilitytool#3]
Hi, just passing on some positive feedback and a question recieved by a user at UCL.

> I just wanted to say that the new accessibility tool for Moodle is great! I wondered if you had heard of specific fonts designed for those with dyslexia? Would those be available in a future iteration? e.g. https://www.dyslexiefont.com/ and there may be others.

Thoughts appreciated. Thanks!

**Comment by sharpchi** [comment]
That's great to hear, thanks for the feedback.

It's a good question about choosing the right font. We spent a bit of time a couple of years ago choosing the right base font for our Moodle that tried to answer the issues that dyslexic users typically have with fonts. I guess that's why we didn't include it as a font in the tool.

We chose it as something everyone would benefit from without choosing. The font we use is PT-Sans (https://fonts.google.com/specimen/PT+Sans). I'll have a think about including it as an optional font to include.

**Comment by sharpchi** [comment]
@evesucl - I've just added the Open Dyslexia font if you'd like to try it.
I can only include open source fonts with the project, so I can't include the dyslexiefont. I was thinking about the possibility of allowing admins to add their own fonts (I can imagine the fonts we have here are of no use to non-latin scripts), but I don't have the capacity currently do this work.
Let me know how your students get on with Open Dyslexia.
thanks
